### ISSUE TITLE
Confusion: Extending Compiler

### ISSUE THREAD

**Issue by apoha-pat** [argyle-engineering/pydantic2zod#136]
Hey there,

This package, at face value, may well be a lifesaver for an application im building, connecting a django backend with a typescript nextjs frontend.

I've started playing around with the library, and the default compiler, but have noticed that theres no first class support for some pydantic features.

Namely:
1) I want to add a new type for date (datetime.datetime --> z.date())
2) I want to extend to capture information from 'Annotated' pydantic types (which for instance, allow conforming a float to a certain range using gt / lt attributes). These would map to zods min() and max() functions

I've tried extending using a custom compiler and overriding the type for these fields, something similar to :

```
class Compiler(pydantic2zod.Compiler):
    def _modify_models(self, pydantic_models: list[ClassDecl]) -> list[ClassDecl]:
        for model in pydantic_models:
            for f in model.fields:
                if f.type == UserDefinedType(name='datetime.datetime'):
                    print(f"found datetime")
                    f.type = LiteralType('z.date()')

        return pydantic_models
```

but this doesnt quite work.

**Comment by povilasb** [comment]
I'll take a look.
In the meantime if you could give some sample pydantic models you have in mind, that would be helpful.

**Comment by povilasb** [comment]
I've added support for `datetime.datetime`:

Say this
```py
from datetime import datetime
from pydantic import BaseModel

class User(BaseModel):
    name: str
    created_at: datetime
```

is translated to
```ts
import { z } from "zod";

export const User = z.object({
  name: z.string(),
  created_at: z.string().datetime(),
}).strict();
export type UserType = z.infer<typeof User>;
```

But note that it's not possible to convert `datetime.datetime` to `z.date()`. e.g. this will error:
```js
const { z } = require('zod');

// Define a schema using Zod
const User = z.object({
    name: z.string().min(2),
    age: z.number().int().positive(),
    email: z.string().email(),
    created_at: z.date()
});

const raw = {
    name: "John Doe",
    age: 25,
    email: "john@example.com",
    created_at: "2021-01-01"
    // created_at: "2021-01-01T00:00:00Z" // errors too
};

const user = User.parse(raw);
console.log("Validation succeeded:", user);
```
See https://zod.dev/?id=dates-1
So that's probably not what you want.

**Comment by povilasb** [comment]
[Added some support](https://github.com/argyle-engineering/pydantic2zod/pull/145) for numerical type constraints:
```py
from typing import Annotated
from pydantic import BaseModel, Field

class Employee(BaseModel):
    age: Annotated[int, Field(ge=18, le=67)]
    level: Annotated[int, Field(1, gt=0, lt=6)]
    salary: Annotated[float, Field(gt=1000, lt=10000)]
```
I'll close this issue.

See if that helps. And if it doesn't, please open a new one with more specific examples.
Thank you.
